function [ ] = tableRender( order, meshDx, roc, rocLag, rocAvg, uyfdm, uyexact, relError )

colLabels0 = {'$\Delta x$', '$\beta(k^2=1)$', '$\beta(k^2=2)$', '$\beta(k^2=5)$', ...
    '$\beta(k^2=10)$', '$\beta(k^2=20)$', '$\beta(k^2=50)$'};
colLabels1 = {'$\Delta x$', '$u''_{k^2=1}(1)$', '$u''_{k^2=2}(1)$', ...
    '$\bar{u}''_{k^2=1}(1)$', '$\bar{u}''_{k^2=2}(1)$', ...
    '$\epsilon''_{rel,k^2=1}$', '$\epsilon''_{rel,k^2=2}$'};
colLabels2 = {'$\Delta x$', '$u''_{k^2=5}(1)$', '$u''_{k^2=10}(1)$',...
    '$\bar{u}''_{k^2=5}(1)$', '$\bar{u}''_{k^2=10}(1)$', ...
    '$\epsilon''_{rel,k^2=5}$', '$\epsilon''_{rel,k^2=10}$'};
colLabels3 = {'$\Delta x$', '$u''_{k^2=20}(1)$', '$u''_{k^2=50}(1)$', ...
    '$\bar{u}''_{k^2=20}(1)$', '$\bar{u}''_{k^2=50}(1)$', ...
    '$\epsilon''_{rel,k^2=20}$', '$\epsilon''_{rel,k^2=50}$'};

if order == 2
    
    matrix2latex([meshDx(1:7)' roc'], 'roc_order_2.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:7)' rocLag'], 'roc_lag_order_2.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:7)' rocAvg'], 'roc_avg_order_2.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(1:2,:)', uyexact(1:2, :)', relError(1:2, :)'], ...
        'qoi_table_1_order_2.tex', 'columnLabels', colLabels1, ...
        'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(3:4,:)', uyexact(3:4, :)', relError(3:4, :)'], ...
        'qoi_table_2_order_2.tex', 'columnLabels', colLabels2, ...
        'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(5:6,:)', uyexact(5:6, :)', relError(5:6, :)'], ...
        'qoi_table_3_order_2.tex', 'columnLabels', colLabels3, ...
        'alignment', 'c', 'format', '%5.4f')
    
    
elseif order == 4
    
    matrix2latex([meshDx(1:7)' roc'], 'roc_order_4.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:7)' rocLag'], 'roc_lag_order_4.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:7)' rocAvg'], 'roc_avg_order_4.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(1:2,:)', uyexact(1:2, :)', relError(1:2, :)'], ...
        'qoi_table_1_order_4.tex', 'columnLabels', colLabels1, ...
        'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(3:4,:)', uyexact(3:4, :)', relError(3:4, :)'], ...
        'qoi_table_2_order_4.tex', 'columnLabels', colLabels2, ...
        'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uyfdm(5:6,:)', uyexact(5:6, :)', relError(5:6, :)'], ...
        'qoi_table_3_order_4.tex', 'columnLabels', colLabels3, ...
        'alignment', 'c', 'format', '%5.4f')
    
end

end

