function [ ] = tableRender( order, meshDx, roc, rocAvg, uxfdm, uxexact, relError, uavgfdm )

colLabels0 = {'$\Delta x$', '$\beta(k^2=1)$', '$\beta(k^2=2)$', '$\beta(k^2=5)$', ...
    '$\beta(k^2=10)$', '$\beta(k^2=20)$', '$\beta(k^2=50)$'};
colLabels1 = {'$\Delta x$', '$u''_{k^2=1}(1)$', '$u''_{k^2=2}(1)$', ...
    '$u''_{k^2=5}(1)$', '$u''_{k^2=10}(1)$', '$u''_{k^2=20}(1)$', '$u''_{k^2=50}(1)$'};
colLabels2 = {'$\Delta x$', '$u_{k^2=1}(1/2, 1/2)$', '$u_{k^2=2}(1/2, 1/2)$', ...
    '$u_{k^2=5}(1/2, 1/2)$', '$u_{k^2=10}(1/2, 1/2)$', '$u_{k^2=20}(1/2, 1/2)$', '$u_{k^2=50}(1/2, 1/2)$'};

if order == 2
    
    matrix2latex([meshDx(1:7)' rocAvg'], 'roc_avg_order_2.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uxfdm(:,:)'], ...
        'qoi_table_1_order_2.tex', 'columnLabels', colLabels1, ...
        'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uavgfdm(:,:)'], ...
        'qoi_table_2_order_2.tex', 'columnLabels', colLabels2, ...
        'alignment', 'c', 'format', '%5.4f')
    
elseif order == 4
    
    matrix2latex([meshDx(1:7)' rocAvg'], 'roc_avg_order_4.tex', ...
        'columnLabels', colLabels0, 'alignment', 'c', 'format', '%5.4f')
    
    matrix2latex([meshDx(1:end)' uavgfdm(:,:)'], ...
        'qoi_table_2_order_4.tex', 'columnLabels', colLabels2, ...
        'alignment', 'c', 'format', '%5.4f')
    
end

end

